apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs1
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs1
  nfs:
    server: 192.168.1.20
    path: "/k8s"

########

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs1
  resources:
    requests:
      storage: 95Mi

########
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-web
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nfs-web
  template:
    metadata:
      labels:
        app: nfs-web
    spec:
      containers:
      - name: nfs-web
        image: nginx:1.18
        volumeMounts:
          - name: nfs
            mountPath: /usr/share/nginx/html
      volumes:
      - name: nfs1
        persistentVolumeClaim:
          claimName: nfs1


